# -*- coding: utf-8 -*-
"""26.05.4potok.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aMK9fNuKgL4WwYWZM24AVmYPixObULdq
"""

print ("Привет мир")